---
date: last-modified
sansfont: Times New Roman
fontsize: 12pt
linkcolor: black
urlcolor: black
author-meta: Devin Judge-Lord
format:
  html: default
  pdf:
    subparagraph: yes
    output-file: judgelord-cv.pdf
    include-in-header:
      text: |
        \usepackage{fontawesome5}
        \usepackage{sectsty}
        \usepackage{parskip}
        \usepackage{titlesec}
        \titlespacing\section{0pt}{12pt plus 4pt minus 2pt}{4pt plus 2pt minus 2pt}
        \titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{4pt plus 2pt minus 2pt}
        \usepackage{hanging}
        % Make lists without bullets
        \renewenvironment{itemize}{
          \begin{list}{}{
            \setlength{\leftmargin}{1.5em}
          }
        }{
          \end{list}
        }
    latex_engine: pdflatex
    geometry:
      - top=1in
      - left=1in
      - bottom=1in
      - right=1in
engine: knitr
# format-links:
#   - text: PDF
#     href: judgelord-cv.pdf
#     icon: file-pdf
#   - pdf: NULL
format-links: false
---


::: {.center data-latex=""}


 \begin{huge} \textbf{Devin Judge-Lord} \end{huge} 

\vspace{5pt}

\hrule

Assistant Professor, University of Michigan

3215 Weill Hall, 735 S State St, Ann Arbor, MI 48109

<i class="bi bi-envelope"></i> \faIcon[regular]{envelope} [judgelor@umich.edu](mailto:judgelor@umich.edu)
| <i class="bi bi-globe"></i> \faIcon[regular]{globe}  [judgelord.github.io](https://judgelord.github.io/)
| *Updated* `r format(Sys.Date(), "%b. %d, %Y")`

\vspace{5pt}

\hrule
:::


# ACADEMIC POSITIONS

\unskip

University of Michigan, Ford School of Public Policy, Assistant Professor (2023-present)

- Faculty Affiliate, Michigan Institute for Data and AI in Society (MIDAS)
- Faculty Affiliate, Science, Technology, and Public Policy program (STPP)

Harvard University, Department of Government, Postdoctoral Fellow (2021-2023)

- Harvard Center for the Environment (HUCE)
- Center for American Political Studies (CAPS)


# EDUCATION

University of Wisconsin--Madison, M.A. (2017) and Ph.D. (2021) in Political Science

- Dissertation: _Public Pressure Campaigns and Bureaucratic Policymaking_
- Committee: Susan Webb Yackee (Chair), Eleanor Powell, Alex Tahk, David Weimer, Miriam Seifter

Yale University, M.E.Sc. in Environmental Policy and Law (2013) <!--Master of Environmental Science  (2013)-->

- Thesis: _Mechanisms of Policy Feedback in U.S. Farm and Forest Policy: Interactions Among Property Rights, Regulation, and Public Investments_ 

Reed College, B.A. in Political Science (2009)

# PEER-REVIEWED PUBLICATIONS

::: {.hanging-indent}


`6.` ["The Effects of Shifting Priorities and Capacity on Policy Work and Constituency Service: Evidence from a Census of Legislator Requests to U.S. Federal Agencies" with Justin Grimmer and Eleanor Powell. *American Journal of Political Science* (2026)](https://doi.org/10.1111/ajps.70031)

- Replication Data: <https://doi.org/10.7910/DVN/LWOCWO>

`5.` ["Campaign Contributions and Bureaucratic Oversight: A Case Study of the Federal Energy Regulatory Commission" with Eleanor Powell and Justin Grimmer in *Accountability Reconsidered: Voters, Interests, and Information in U.S. Policymaking*, ed. Charles M. Cameron, Brandice Canes-Wrone, Sanford C. Gordon, Gregory A. Huber, Cambridge University Press (2023)](https://judgelord.github.io/research/ferc/)


`4.` ["Mapping Literature with Networks: An Application to Redistricting" with Adeline Lo, Kyler Hudson, Kenneth R. Mayer. *Political Analysis* (2023)](https://doi.org/10.1017/pan.2023.4)


`3.` ["Data and Methods for Analyzing Interest Group Influence in Rulemaking" with Daniel Carpenter, Brian Libgober, Steven Rashin. *Interest Groups & Advocacy* 9:425–435 (2020)](https://doi.org/10.1057/s41309-020-00094-w)

`2.` ["Do Private Regulations Ratchet Up? How to Distinguish Types of Regulatory Stringency and Patterns of Change" with Benjamin  Cashore and Constance McDermott in *Organization \& Environment* 33:1 96–125 (2020)](https://doi.org/10.1177/1086026619858874)

`1.` ["Non-domestic Sources of Canadian Boreal Forest Policy: Integrating Theories of Internationalization and Pathways of Policy Change" with Irene Scher and Benjamin Cashore in *Forests Under Pressure: Local Responses to Global Issues* (2015)](https://judgelord.github.io/research/boreal)

:::

# WORKING PAPERS

<!--
"The Two Faces of Bureaucratic Policymaking: Before and after draft rules go public" with Susan Yackee
--> 


["Words and Deeds: Evaluating How Legislators’ Constituent-Facing Communication about Federal Agencies Compares to Their Behind-the-Scenes Work with Federal Agencies" with Jessie Munson, Rochelle Snyder, Eleanor Neff Powell]() (MPSA 2025, under review)

["Inequality in Administrative Democracy: Methods and Evidence from Financial Rulemaking" with  Steven Rashin,  Brian Libgober, Jacob Waggoner,  Angelo Dagonel, Christopher T. Kenny, Susan Webb Yackee, and Daniel Carpenter ](https://judgelord.github.io/research/finreg/) (APSA 2021, submitted) 

- *Herbert Kaufman Award for best paper in Public Administration presented at APSA 2022* 

["Racialization and Perceived Institutional Ideology" with Karla Magana](https://judgelord.github.io/racialization/mpsa-presentation.html) (MPSA 2025) 

[“Adoption and Cooption of the Environmental Justice Issue Frame”](https://judgelord.github.io/ej/APSA2024.html) (APSA 2024)

["Iterative Hand-Coding and Computational Text Analysis"](https://judgelord.github.io/research/iterative) (PolMeth 2022)
<!--: Application to Assessing the Effects of Public Pressure on Policy-->

["Making Policy About Distributive Justice: The Environmental Justice Movement's Impact on Agency Rulemaking"](https://judgelord.github.io/research/ej/) (APSA 2021)

["Making Policy About Climate Change: The Climate Movement's Impact on Agency Rulemaking"](https://judgelord.github.io/research/cj/) (Climate Pipeline Conference 2021)

["Who Gets Constituent Service?" with Rochelle Snyder, Justin Grimmer, and Eleanor Powell](https://judgelord.github.io/research/correp/) (APSA 2020)

["Why Do Agencies (Sometimes) Get So Much Mail? Lobbying Coalitions, Mass Comments, and Political Information in Bureaucratic Policymaking"](https://judgelord.github.io/research/whymail/) (SPSA 2019)

["Measuring Change and Influence in Budget Texts" ](https://judgelord.github.io/research/budgets) (PolMeth 2017, APSA 2017)

["Why Courts Defer to Administrative Agency Judgement"](https://judgelord.github.io/research/defrence/) (MPSA 2016)

<!-- "U.S. Domestic Politics of Climate Engineering" (AESS 2016)
--->

"Revisiting the Democratic Case for Carbon and Environmental Offset Markets" (Governance, Environment, and Markets Workshop at Yale University, 2013) 

<!--"Mechanisms of Policy Feedback: Interactions Among Regulations and Public Investments in U.S. Farm and Forest Politics" (MESc Thesis, Yale University 2013)-->


# OTHER PUBLICATIONS

"Institutional Changes Needed to Implement Ecosystem-based Plans" with John Robert Cochran, *Oregon Planners Journal* 28(1):7 (2011)

# SOFTWARE 

[`regulationsdotgov`: A package to build datasets of US federal policy documents and their metadata in R](https://judgelord.github.io/regulationsdotgov/)

[`netlit`: A package to aid literature reviews with network analysis in R](https://judgelord.github.io/netlit/)

[`legislators`: A package to find legislator names in messy text ](https://judgelord.github.io/legislators/)

[`congressionalrecord`: A package to scrape, parse, and analyze the Congressional Record](https://judgelord.github.io/congressionalrecord/)

[`regextable`: Faster, easier, string matching for data science](https://judgelord.github.io/regextable)

# TEACHING

University of Michigan, Assistant Professor

- Protest, Social Movements, Art, and Policy Change (Graduate, 2026)

- Climate Change and Democracy (Undergraduate, 2024, 2025)

- Politics for the Anthropocene (Undergraduate, 2024, 2025)

- The Politics of Public Policy (Graduate, 2023, 2024, 2025)

- Independent Study - Political Science (Undergraduate, 2024-2026)

University of Wisconsin--Madison, Lecturer

- Public Policy (Undergraduate, 2019, 2020)

- Statistical Computing in Political Science (Graduate, 2019)

University of Wisconsin--Madison, Teaching Assistant/Grader

- Public Policy (Undergraduate, 2016, 2017, 2018)

- Policing in the United States (Undergraduate, 2015)

Yale University, Teaching Fellow

- The Politics and Practice of Environmental Policy (Graduate, 2012)

- The Economics of Ecosystems and Biodiversity (Graduate, 2011)


# SELECTED AWARDS

Teaching Honor Roll, University of Michigan (2024, 2025, 2026)

Best Paper in Public Administration, American Political Science Association conference: "Inequality in Administrative Democracy" (2022)

Best Dissertation in American Politics, University of Wisconsin--Madison (2021)

Levin Center Congressional Oversight Fellow (2021-2022)

National Science Foundation (NSF) Doctoral Dissertation Research Improvement Grant (2020) <!--, awarded by the American Political Science Association (APSA) -->

Exceptional Mentorship Award, Undergraduate Research Scholars Program, UW--Madison (2020)

Summer Research Initiative Research Award, UW--Madison (2018, 2019, 2020, 2021)

La Follette Fellowship, University of Wisconsin La Follette School of Public Affairs (2016)

Finalist, Best Student Paper, Association of Environmental Studies and Sciences (2015)

Best Master's Thesis Research Award (runner-up), selected by faculty among all social and natural science Masters Theses (Yale School of the Environment, 2013)

Best Student Paper Award, Association for Environmental Studies and Sciences (2012)

Carpenter-Sperry Research Award (2012)

Jubitz Family Foundation Research Fellowship (2012)

H. Stuart Harrison Scholarship to attend Yale University (2011–2013)

Morton O'Stafford Scholarship to attend Reed College (2006–2009)

Pell Grant (2005-2009)




# PUBLIC POLICY AND RESEARCH POSITIONS

Visiting Scholar, New York University, Department of Politics (2021-2022)

Affiliated Researcher, Yale Governance, Environment, and Markets (GEM) Initiative (2013–2020)

Research Consultant, Food and Agriculture Organization of the United Nations (2013–2014)

- Compared forestry laws across countries with quantitative and qualitative text analysis

- Wrote policy-focused portions of the State of the World's Forests Report

Regulatory Affairs Specialist, Washington County, Oregon (2010–2011) 

- Convened state and federal agency staff to draft Oregon Department of Environmental Quality Guidance 

- Drafted text for an Oregon State Senate bill 

- Conducted a feasibility analysis that led to \$10 million in private conservation investment, \$1 million in public investment, and praise for the project in a speech by President Barack Obama

Ducey Fellow for Public Policy, Willamette Partnership (2009)

Research Intern, Center for Transboundary Cooperation, Saint-Petersburg State University, Russia (2008)




# SERVICE


PhD Program Committee, Ford School of Public Policy (2024-2026)

Water@Michigan Faculty Steering Committee 

Faculty Supervisor, U.S. State Department/Weiser Diplomacy Center Diplomacy Lab project assisting the Department of the Treasury adoption of Office of Management and Budget (OMB) circulars A-4 2003 and 2023 (2024-2025)

Masters Program Committee, Ford School of Public Policy (2023-2024)

Reviewer: *American Political Science Review*, *Journal of Public Administration Research and Theory*, *Journal of Politics*, *Journal of Public Policy*, *Perspectives on Politics*, *Regulation \& Governance*, *Current Opinion in Sustainability*, *Journal of Forest Policy and Economics*

Social Media Editor (2017-2024), American Political Science Association section on Science, Technology, and Environmental Politics (APSA STEP) 

Program Committee (2014–2016), Nominations Committee (Elected, 2016-2022), Association of Environmental Studies and Sciences (AESS) 

<!--
PhD Advisor

- Branden Bohrnsen
--> 

Dissertation Committees

- Karla Magana  (University of Michigan, Political Science and Public Policy)
- Maya Khuzam (University of Michigan, Political Science)


Mentor, Undergraduate Research Opportunity Program (UROP), University of Michigan (2023-present)

- Mentees: 
Antonio Isho,
Lily Bourgeois, 
Jesse Duby, 
Niyatee Jain, 
Grace Lee, 
Scotten Maderal, 
Arvin Pandiyan, 
Ava Malin,
Farah Kavarana,
Genevieve Fettig,
Meiting Xu,
Mia Alderman,
Samantha Lay,
Shakuntala Balusu,
Scotten Maderal,
Summit Shaw,
Jessica Rehberg,
Zayn Merrick,
Emma Weiss,
Aya Soweidan,
Naya Ramaswami,
Brody	Amthor,
Stephanie	Bouserhal,
Justin	Chen,
Lyndon	Dibble,
Aamir	Kapasi,
Madison	Knowlton,
Ashanti	Mirelez,
Kaito	Patterson,
Olivia	Savord,
Audrey	Stocker,
Gia	Verma,
Evan	Weinraub,
Anna	Childs,
Shirlyn	Dong,
Isabella	Gentry,
Steven	Kang,
Anna	Kendzior,
Ryan	Rincones,
Aaron	Zhao,
Kaito Patterson

<!-- Other Lab Members 
Karla Magana <kmagana@umich.edu>,
Gavriella Solomon <gavriell@umich.edu>,
Emily Laffey <emlaffey@umich.edu>,
Amant Grewal
Luke Dillingham ,
Deven Parikh
Julian 
Saman de Silva
Maya Khuzam
Will Cooper
--> 

Supervisor, Honors Thesis (University of Michigan)

- Jessica Rehberg (2025-2026)

Supervisor, Directed Study (University of Michigan)

- Gavriella Solomon, Emily Laffey  (2024-2025)

Co-supervisor, Undergraduate Thesis (Harvard College)

- Robin Greene (2023-2024)

Mentor, Harvard University Center for the Environment (HUCE) Undergraduate Research Scholars Program (2022-2023)

- Mentees: Davit Antonyan, Robin Greene, Tomoki Matsuno


Mentor, Undergraduate Research Scholars Program, UW--Madison (2015-2021)

- Mentees: Kendl Kobbervig, Kyra Fox, Mikayla Sandin, Daniel Nesslein, Hope Karnopp, Julia Derzay, Samiha Bhushan, Max Linse, Hailey Patel

Mentor, Sophomore Research Fellows Program, UW--Madison (2021)

- Mentee: Samiha Bhushan

Supervisor, Honors Theses and Directed Studies, UW--Madison (2020-2021)

- Students: Maggie Nead, Fatima Ali, Samiha Bhushan

Diversity and Inclusion Committee, UW--Madison Department of Political Science (2019-2021)

Reading Room Committee, UW--Madison Department of Political Science (2016-2019)

Graduate School Representative, Associated Students of Madison Student Council  (2016-2017)

Vice-Chair (2012–2013), Workshops Chair (2011–2012), New Directions in Environmental Law conference at Yale Law School

President, Yale Environmental Law Association Student Interest Group (2012–2013)

<!--
# INVITED TALKS

Yale Conference on Politics and Law in the Administrative State - "Agencies and Stakeholders" (2025)

University of Mississippi "The Environmental Justice Movement's Impact on Technocratic Policymaking" (2021)


# CERTIFICATIONS

Inclusive Teaching (4-day workshop, University of Wisconsin--Madison, 2020)

Teaching in the Social Sciences Certificate (Yale University, 2012)

<!--River Restoration Professional Certificate (Portland State University, 2011)-->


<!--
# LANGUAGES

English (native), Spanish (conversational), Russian (basic), R, Python,  Stata, SQL, SPSS, Mathematica, Markdown, \LaTeX, HTML

# SELECTED COURSEWORK IN LAW

*Yale Law School*: Administrative Law; Energy Law; Property Law; Environmental Law; Land Use Law; Property, Social Justice, and the Environment

# SELECTED COURSEWORK BUSINESS ADMINISTRATION

*Yale School of Management*: Corporate Environmental Management and Strategy


<!--
# REFRENCES 

Susan Webb Yackee  
Director, La Follette School of Public Affairs  
Professor of Public Affairs and Political Science  
University of Wisconsin--Madison  
yackee@wisc.edu  
(608) 886-5215  


Eleanor Neff Powell  
Booth Fowler Associate Professor of Political Science  
University of Wisconsin--Madison  
eleanor.powell@wisc.edu  
(857) 991-9536  


<!--
# SELECTED GRADUATE COURSEWORK

*Yale School of Forestry and Environmental Studies*: Political Economy (an independent study structured around the Political Economy Workshop in the Department of Political Science); Research and Writing in the Social Sciences; Corporate Environmental Strategy and Management; International Environmental Policy & Governance

*Yale University, Department of Political Science*: Qualitative Field Research; The People

*University of Wisconsin--Madison, Department of Political Science*: Economic Inequality in Modern Political Thought; Race and Politics in the U.S.; Empirical Methods of Political Inquiry, Statistics in Political Science, Macro-theories of American Politics; The Legislative Process: Classics in American Politics; Maximum Likelihood Estimation; Game Theory & Political Analysis; Statistical Computing; Statistical Inference; Experimental Methods; Bayesian Statistics



Project Assistant, University of Wisconsin--Madison (2015-Present)




---

PRESENTATIONS

American Political Science Association (2017, 2018)

Midwest Political Science Association (2016, 2020)

Association of Environmental Studies and Sciences Annual Conference (2012, 2018, 2019, 2020)

New Directions in Environmental Law Conference, Yale Law School (2012, 2013)

What if Plans Were the Law? with Professor Christopher Serkin. New Directions in Environmental Law Conference.
New Haven, CT. Mar. 2, 2013
Politics in Market Design: Stakeholder participation in U.S. water quality trading programs. Association of Environmental
Studies and Sciences 2012 Annual Conference. Santa Clara, CA. Jul. 21, 2012.
Old Laws, New Problems: Evolving strategies for water quality with Professor Ann Powers and Attorney Tom Lindley,
New Directions in Environmental Law conference. New Haven, CT. Feb. 25, 2012.
Ecosystem Markets 101 with Tracy Stanton and How Do Ecosystem Services Stack Up? panel presentation with Professor
Richard Woodward and Jimmy Duakas, moderated by Lydia Olander. The American Forest Foundation and World
Resources Institute's 4th annual Ecosystem Markets Conference. Madison, WI. Jun. 29, 2011.
Standards of Ecosystem Credit Accounting (and points of negotiation). California Roundtable on Agriculture and the
Environment. San Francisco, CA. Nov. 1, 2010.
Building Unique Local Markets With Shared Regional Infrastructure. Northwest Environmental Forum. University of
Washington, Seattle. Oct. 18, 2010.
Counting on the Environment: Salmonid, Wetland, and Prairie Habitat metrics. The American Forest Foundation and
World Resources Institute's 3rd Annual Environmental Markets Conference. Raleigh, NC. Jul. 22, 2010.

Travel Grant (Yale University 2011, 2012)






SKILLS AND LANGUAGES
R; Python; SPSS; Stata; Mathematica; basic ArcGIS; NVivo; Atlas.TI
Conversational Russian; basic Spanish


Discussant, Midwest Political Science Association (MPSA) annual conference (2015, 2016)

- Thesis: _Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments_
Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments in U.S. Farm and Forest Politics

- Thesis: _Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments_

Research Assistant, Governance, Environment, and Markets (GEM) Initiative
• Analyzed methods employed in 220 journal articles


• Developed regulatory compliance strategies, convening state and federal agencies to secure a memorandum of understanding
on Clean Water Act compliance (now Oregon Department of Environmental Quality Guidance)
• Drafted legal language for an Oregon State Senate bill
• Conducted a feasibility analysis that led to \$10 million in private investment, $1 million
in public investment, and praise for the project in a speech by President Barack Obama



# REFERENCES

Daniel Carpenter    
Allie S. Freed Professor of Government  
Harvard University  
dcarpenter@gov.harvard.edu
 
Susan Webb Yackee  
Director, Robert M. La Follette School of Public Affairs  
Professor of Public Affairs  
University of Wisconsin--Madison  
yackee@wisc.edu

Eleanor Powell  
Booth Fowler Associate Professor of Political Science  
University of Wisconsin--Madison  
eleanor.powell@wisc.edu

David Weimer  
Edwin E. Witte Professor of Political Economy  
Robert M. La Follette School of Public Affairs  
University of Wisconsin--Madison  
weimer@lafollette.wisc.edu

Benjamin Cashore  
Li Ka Shing Professor in Public Management  
Director, Institute for Environment and Sustainability  
Lee Kuan Yew School of Public Policy  
sppbwc@nus.edu.sg
-->