---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/judgelord.github.io/cv/svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Devin Judge-Lord

jobtitle: no
address: "110 North Hall, 1059 Bascom Mall, Madison, WI 53706"
fontawesome: yes
email: "JudgeLord@Wisc.edu"
github: judgelord
twitter: judgelord
phone: "715.204.4287"
web: no
updated: yes

keywords: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: black
urlcolor: black
---

# EDUCATION

University of Wisconsin-Madison, Ph.D. in Political Science (2015-present, M.A. received 2017)

Yale University, Master of Environmental Science (2013)

Reed College, B.A. (2009)

# PEER-REVIEWED PUBLICATIONS

"Non-domestic Sources of Canadian Boreal Forest Policy: Integrating theories of internationalization and pathways of policy change." with Irene Scher and Benjamin Cashore. [Peer-reviewed book chapter] In *Forests Under Pressure: Local Responses to Global Issues.* 

# WORKING PAPERS

"Do Private Regulations Ratchet Up?: How to distinguish types of regulatory stringency and patterns of change" with Benjamin Cashore and Constance McDermott [R\&R at *Organization \& the Environment*]

"Why Do Agencies (sometimes) Get So Much Mail? Lobbying coalitions, mass comments, and political information in bureaucratic policymaking" (SPSA 2019)

"How Legislators Actually Spend Their Time: Constituents, donors, or policy" with Justin Grimmer and Eleanor Powell (APSA 2018)

"Social Movements, Science, Bureaucracy, and Democracy: How mobilizing for environmental justice influences technocratic policymaking" (AESS 2018)

"Measuring Change and Influence in Budget Texts" (PolMeth 2017, APSA 2017)

"How Do Forest Certification Policies Change Over Time?: Comparing Sustainable Forestry Initiative and Forest Stewardship Council Standards in the United States, 2008-2015" (APPAM 2015)

# OTHER PUBLICATIONS

"Institutional Changes Needed to Implement Ecosystem-based Plans." with John Robert Cochran. *Oregon Planners Journal* 28(1): 7. 

# CONSULTING

Affiliated Researcher, Yale Governance, Environment, and Markets (GEM) Initiative (2013–Present)

- Developed methods to systematically compare forestry certification standards

Research Consultant, Arup Group (2015)

- Developed decision tool for timber sourcing

Research Consultant, Food and Agriculture Organization of the United Nations (2013–2014)

- Researched and wrote chapters of the *State of the World's Forest Report*

Regulatory Affairs Specialist, Willamette Partnership and Washington County, Oregon (2010–2011) 

- Convened state and federal agency staff to draft Oregon Department of Environmental Quality Guidance 

- Drafted text for an Oregon State Senate bill 

- Conducted a feasibility analysis that led to \$10 million in private conservation investment, \$1 million in public investment, and praise for the project in a speech by President Barack Obama

Ducey Fellow for Public Policy, Willamette Partnership (2009)

# TEACHING

University of Wisconsin-Madison, Instructor

- Statistical Computing in Political Science (Graduate, 2019)

# TEACHING ASSISTANT & GRADER POSITIONS

University of Wisconsin-Madison

- Public Policy (Undergraduate, 2016, 2017, 2018)

- Policing in the United States (Undergraduate, 2015)

Yale University

- The Politics and Practice of Environmental Policy (Graduate, 2012)

- The Economics of Ecosystems and Biodiversity (Graduate, 2011)


# SELECTED AWARDS

Finalist, Best Graduate Student Paper, Association of Environmental Studies and Sciences (2015)

Best Master’s Thesis Research Award (runner-up), selected by faculty among all social and natural science Master's Thesis Colloquia presentations (Yale University, 2013)

Best Student Research Presentation, Association for Environmental Studies and Sciences (2012)

Carpenter-Sperry Research Award (2012)

Jubitz Family Foundation Research Fellowship (2012)

H. Stuart Harrison Scholarship (Yale University 2011–2013)


# SERVICE

Referee: *Regulation \& Governance*, *Journal of Forest Policy and Economics*

Social Media Editor (2017-present), American Political Science Association Science, Technology, and Environmental Politics section (APSA STEP) 

Program Committee (2014–2016), Nominations Committee (2016-present), Association of Environmental Studies and Sciences (AESS) 

Mentor, Undergraduate Research Scholars Program, UW-Madison (2015–2017)

Vice-Chair (2012–2013), Workshops Chair (2011–2012), New Directions in Environmental Law Conference at Yale Law School








```{extra, include = FALSE}


# CERTIFICATIONS

Teaching in the Social Sciences Certificate (Yale University, 2012)


- Committee: Susan Yackee (chair), Eleanor Powell, Alex Tahk, Dave Weimer, Miriam Seifter


Project Assistant, University of Wisconsin-Madison (2015-Present)


"The Two Faces of Bureaucratic Policymaking: Before and after draft rules go public" with Susan Yackee

"U.S. Domestic Politics of Climate Engineering" (AESS 2016)

---
PRESENTATIONS

American Political Science Association (2017, 2018)

Midwest Political Science Association (2016)

Association of Environmental Studies and Sciences Annual Conference (2012, 2018)

New Directions in Environmental Law Conference, Yale Law School (2012, 2013)


Travel Grant (Yale University 2011, 2012)


President, Yale Environmental Law Association Student Interest Group (2012–2013)



SKILLS AND LANGUAGES
R; Python; SPSS; Stata; Mathematica; basic ArcGIS; NVivo; Atlas.TI
Conversational Russian; basic Spanish


Discussant, Midwest Political Science Association (MPSA) annual conference (2015, 2016)

- Thesis: _Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments_
Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments in US Farm and Forest Politics

- Thesis: _Mechanisms of Policy Feedback: Interactions among Regulations and Public Investments_

Research Assistant, Governance, Environment, and Markets (GEM) Initiative
• Analyzed methods employed in 220 journal articles


• Developed regulatory compliance strategies, convening state and federal agencies to secure a memorandum of understanding
on Clean Water Act compliance (now Oregon Department of Environmental Quality Guidance)
• Drafted legal language for an Oregon State Senate bill
• Conducted a feasibility analysis that led to \$10 million in private investment, $1 million
in public investment, and praise for the project in a speech by President Barack Obama
```